model:
  name: "retinanet"
  backbone: "resnet50"
  num_classes: 2  # Background and tick
  pretrained: true
  freeze_backbone: false
  min_size: 1024  # Keep 1024 for tick detection
  max_size: 1024  # Keep 1024 for tick detection
  box_score_thresh: 0.3  # Increased from 0.05 to reduce false positives
  box_nms_thresh: 0.5
  box_detections_per_img: 20  # Reduced from 100 to limit detections per image
  anchor_sizes: [32, 64, 128, 256, 512]  # Reduced anchor sizes for better tick detection
  anchor_ratios: [0.5, 1.0, 2.0]  # Good for oval/elliptical ticks

data:
  train_paths:
    - "data/chunk_001/images"
    - "data/chunk_002/images"
    - "data/chunk_003/images"
    - "data/chunk_004/images"
    - "data/chunk_005/images"
  train_annotations:
    - "data/chunk_001/annotations.json"
    - "data/chunk_002/annotations.json"
    - "data/chunk_003/annotations.json"
    - "data/chunk_004/annotations.json"
    - "data/chunk_005/annotations.json"
  val_split: 0.2
  input_size: [1024, 1024]  # Keep 1024x1024 for tick detection
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  categories:
    - id: 0
      name: "tick"
    - id: 1
      name: "background"

training:
  device: "cuda"
  num_epochs: 100  # Keep longer training for high resolution
  batch_size: 8    # Reduced for stability
  learning_rate: 0.0003  # Reduced for better stability
  weight_decay: 0.0001
  
  min_epochs: 15
  early_stopping_patience: 10
  
  lr_scheduler:
    name: "reduce_on_plateau"
    factor: 0.5
    patience: 10
    min_lr: 0.00001
  
  gradient_clip: 10.0
  
  num_workers: 4
  pin_memory: true
  prefetch_factor: 2
  persistent_workers: true
  
  use_amp: true
  channels_last: true
  
  allow_tf32: true

output:
  checkpoint_dir: "outputs/training/checkpoints"
  output_dir: "outputs"
  training_curves: "outputs/training/curves"
  evaluation_dir: "outputs/evaluation"

augmentation:
  train:
    horizontal_flip: true
    vertical_flip: true
    rotate:
      enabled: true
      limit: 45
    scale:
      enabled: true
      min: 0.8
      max: 1.2
    brightness:
      enabled: true
      limit: 0.2
    contrast:
      enabled: true
      limit: 0.2
    blur:
      enabled: true
      limit: 3
    noise:
      enabled: true
      limit: 0.05
  
  val:
    resize_only: true

classes:
  0: "tick"

paths:
  checkpoint_dir: "checkpoints"
  output_dir: "outputs" 
